volumes:
  griffin-db-data:

services:
  typesense:
    image: typesense/typesense:27.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'

  db:
    image: postgres:17
    volumes:
      - griffin-db-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=griffin
      - POSTGRES_PASS=griffin
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_PASSWORD=griffin
    ports:
      - 5432:5432
