volumes:
  postgis-data:
  pgadmin-data:

services:
  db:
    image: postgis/postgis:14-3.4-alpine
    volumes:
      - postgis-data:/var/lib/postgresql
    environment:
      - POSTGRES_USER=yardzen
      - POSTGRES_PASS=yardzen
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_PASSWORD=yardzen
    ports:
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: griffin.mahoney@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin-data:/var/lib/pgadmin