name: prod

volumes:
  db-data-prod:
  typesense-data-prod:


services:
  typesense:
    container_name: griffin-typesense-prod
    image: typesense/typesense:27.0
    restart: on-failure
    ports:
      - "8108:8108"
    volumes:
      - ./typesense-data-prod:/data
    command: '--data-dir /data --api-key=xyz --enable-cors'

  db:
    container_name: griffin-db-prod
    image: postgres:17
    volumes:
      - db-data-prod:/var/lib/postgresql
    environment:
      - POSTGRES_USER=griffin
      - POSTGRES_PASS=griffin
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_PASSWORD=griffin
    ports:
      - 5432:5432
  api:
    container_name: griffin-api-prod
    image: griffin-api:latest
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "10100:8080"
    depends_on:
      - db
      - typesense
    restart: on-failure

  ui:
    container_name: griffin-ui-prod
    image: griffin-ui:latest
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "10200:8080"
    depends_on:
      - api
    restart: on-failure
