apiVersion: v1
kind: Service
metadata:
  name: notes-api
  namespace: prod
  labels:
    app: notes-api
spec:
  type: ClusterIP
  ports:
  - port: 10301
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: notes-api

