apiVersion: v1
kind: Service
metadata:
  name: notes-ui
  namespace: prod
  labels:
    app: notes-ui
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30300
    protocol: TCP
    name: http
  selector:
    app: notes-ui

